services:
  web:
    build: .
    image: monetise
    ports:
      - '7777:1337'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS=--max_http_header_size=65536
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5233:5432'
    environment:
      # PGUSER: 'postgres'
      POSTGRES_USER: 'monetise'
      POSTGRES_PASSWORD: 'monetise_password'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monetise"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgresqldata: