services:
  web:
    build: .
    image: monetise
    ports:
      - '7777:1337'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS=--max_http_header_size=65536
    volumes:
      - ./data:/usr/app/Thalia/websites/monetise/data
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.4.7
    volumes:
      - mariadbdata:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '5233:3306'
    environment:
      MYSQL_DATABASE: monetise
      MYSQL_USER: monetise
      MYSQL_PASSWORD: monetise_password
      MYSQL_ROOT_PASSWORD: monetise_root_password
    restart: always
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 1s
      retries: 5

volumes:
  mariadbdata:
